FROM alpine:3.22@sha256:310c62b5e7ca5b08167e4384c68db0fd2905dd9c7493756d356e893909057601

RUN apk add --no-cache \
    bash \
    curl \
    ca-certificates \
    coreutils \
    util-linux \
    parted \
    dosfstools \
    e2fsprogs \
    mtools \
    grub \
    grub-efi \
    xz \
    tar \
    zstd \
    rsync \
    findutils \
    grep \
    gawk \
    sed \
    shadow \
    gzip \
    bzip2 \
    kmod

WORKDIR /work
